### ISSUE TITLE
Background-image not showing from CSS file

### ISSUE THREAD

**Issue by Stefanocalo** [Stefanocalo/Plant_site#1]
Hi everyone. 

Unfortunately when displaying my website online it's not showing the background images from style.css. (https://github.com/Stefanocalo/Plant_site/blob/b4e4edf6cfc6ba07daae7332816246675c97d57c/Plant_Website/style/style.css)

I've tried to change the images path but I really can't understand why they are not showing up. 
When trying locally everything is displaying correctly. 

Any help is very apprecciated.

**Comment by memer-s** [comment]
Could you elaborate on how you are hosting the website?

**Comment by memer-s** [comment]
#2 will fix your issue. 
I would recommend you to move the style.css file out of the style folder to ./Plant_site/style.css, for index.html and style.css to have a shared root; if you would want it to work both online and locally.
